In [2]:
import numpy as np
#create array
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [3]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)


In [4]:
#change arr
arr=np.arange(10)

print (arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Lets see the original save copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [18]:
#Saving multiple arrays into a zip file
arr1=np.array([[10,20,30,40,50],[60,70,80,90,100]])
arr2=np.array([[11,21,31,41,51],[61,71,81,91,101]])
print (arr1)
print(arr2)

np.savez("my_arry1",x=arr1,y=arr2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 11  21  31  41  51]
 [ 61  71  81  91 101]]


In [20]:
#Now loading multiple arrays

file_1=np.load("my_arry1.npz")
print (file_1['x'])
print (file_1['y'])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 11  21  31  41  51]
 [ 61  71  81  91 101]]


In [50]:
np.rm('my_arr1')
rm 'my_arr2.npz'

SyntaxError: invalid syntax (<ipython-input-50-8c18c9219b03>, line 2)

In [56]:
#Now saving and loading text files
arr2=np.array(([1,2,3],[3,4,5],[7,8,9]),dtype=np.int)

np.savetxt('my_arr_textfile.txt',arr2,delimiter=',',header="This is Sample Text File",footer='Sample  Footer')

In [57]:
#Load Excel file

opentext=np.loadtxt('my_arr_textfile.txt',delimiter=',')
print(opentext)

[[ 1.  2.  3.]
 [ 3.  4.  5.]
 [ 7.  8.  9.]]
