In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Squire root of array
print ("#Squire root of array")
np.sqrt(arr)

#Squire root of array


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
#Exponential for numpy
print("#Exponential for numpy")
np.exp(arr)

#Exponential for numpy


array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
#Create array using random function
print ("#Create array using random function")
A=np.random.randn(10)
A

#Create array using random function


array([ -3.76272317e-01,   1.13165599e+00,   4.58682081e-01,
         2.54200823e-01,   1.67141960e-04,  -1.94238004e+00,
         1.41438960e-01,  -9.70090908e-01,  -1.11927669e+00,
        -2.95417517e-01])

In [11]:
B=np.random.randn(10)
B

array([-0.38312417, -2.6789634 ,  0.28679731,  0.00734161,  0.13796697,
        1.50038256,  0.57115869, -0.74879758, -0.11332728,  0.40495805])

In [12]:
np.add(A,B)

array([-0.75939648, -1.5473074 ,  0.7454794 ,  0.26154244,  0.13813411,
       -0.44199748,  0.71259765, -1.71888848, -1.23260396,  0.10954053])

In [13]:
np.maximum(A,B)

array([-0.37627232,  1.13165599,  0.45868208,  0.25420082,  0.13796697,
        1.50038256,  0.57115869, -0.74879758, -0.11332728,  0.40495805])

In [15]:
np.minimum(A,B)

array([ -3.83124168e-01,  -2.67896340e+00,   2.86797315e-01,
         7.34161233e-03,   1.67141960e-04,  -1.94238004e+00,
         1.41438960e-01,  -9.70090908e-01,  -1.11927669e+00,
        -2.95417517e-01])

In [20]:
weburl='http://docs.scipy.org/doc/numpy/reference/ufuncs.html#availanle-ufuncs'
import webbrowser
webbrowser.open(weburl)

True