In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1=Series([0,1,2],index=['T','U','V'])

ser2=Series ([3,4],index=['X','Y'])

ser2

X    3
Y    4
dtype: int64

In [7]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [9]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])


In [12]:
dframe1

X         Y         Z
0 -0.328750 -1.424340  0.326069
1 -1.482637 -1.242029  0.624762
2  0.617515 -1.429788  0.182322
3  0.834877  0.610362  0.680631

In [13]:
dframe2

Y         Q         X
0 -0.703674 -0.621422 -1.878563
1  0.698392  0.771366 -0.805622
2 -0.203956 -0.614118  1.535464

In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.328750 -1.424340  0.326069
1       NaN -1.482637 -1.242029  0.624762
2       NaN  0.617515 -1.429788  0.182322
3       NaN  0.834877  0.610362  0.680631
0 -0.621422 -1.878563 -0.703674       NaN
1  0.771366 -0.805622  0.698392       NaN
2 -0.614118  1.535464 -0.203956       NaN

In [21]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.328750 -1.424340  0.326069
1       NaN -1.482637 -1.242029  0.624762
2       NaN  0.617515 -1.429788  0.182322
3       NaN  0.834877  0.610362  0.680631
4 -0.621422 -1.878563 -0.703674       NaN
5  0.771366 -0.805622  0.698392       NaN
6 -0.614118  1.535464 -0.203956       NaN

In [ ]:
url='http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.cocate.html'