In [1]:
import numpy as np
#Creating Array
my_list1=[1,2,3,4,5]
my_list1

[1, 2, 3, 4, 5]

In [2]:
#create array by passing list
my_array1=np.array(my_list1)
my_array1

array([1, 2, 3, 4, 5])

In [5]:
my_list2=[11,12,13,14,15]
my_lists=[my_list1,my_list2]
print (my_lists)

[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]]


In [7]:
#Create Multi dimecitional array
my_array2=np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [8]:
#get the share of the Array
my_array2.shape

(2, 5)

In [13]:
#get type of the array
my_array2.dtype

dtype('int32')

In [14]:
my_array1.dtype

dtype('int32')

In [30]:
#Create Array with all Zeros (Data type Floting)
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [41]:
#Create Zero array
s = (2,2)
np.zeros((s),dtype=int)

array([[0, 0],
       [0, 0]])

In [34]:
#Create Array with all zeros (Data type Floting)
np.zeros((5,3),dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
my_zeros_array=np.zeros(5)
my_zeros_array.dtype

dtype('float64')

In [35]:
np.ones([5,5], dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.empty(5)

array([  6.78802016e-312,   6.19076424e+223,   4.72218500e+257,
         4.17339994e+199,   3.03837564e+180])

In [39]:
np.eye((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])