In [3]:
import numpy as np
int(5/2)

2

In [4]:
5/2

2.5

In [5]:
5.0/2

2.5

In [21]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [23]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
arr1 * 3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [25]:
arr1/arr1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [32]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [34]:
arr1**5

array([[    1,    32,   243,  1024],
       [ 3125,  7776, 16807, 32768]], dtype=int32)