In [26]:
import numpy as np
arr = np.arange(0,11)

#Display array without print method
print ("# Display array without print method")
arr

# Display array using print method
print ("# Display array using print method")
print (arr)


# Display the value by array Index
print ("# Display the value by array Index without print method")
arr[8]

# Display the array elements from index 1 to 5
print ("# Display the array elements from index 1 to 5")

print (arr[1:5])
arr [1:5]

#Change the array value from index 0 to 5

arr[0:5]=100
arr

#Recreate the array once again with the same variable arr
arr=np.arange(0,11)
arr

#Sclicing array
print ("#Sclicing array")
slice_of_Ary= arr[0:6]

slice_of_Ary

#Change the value in the slice_of_array
print ("#Change the value in the slice_of_array")
slice_of_Ary[2:4]=90

slice_of_Ary

#pring list of arr item after slicing
arr

#copy a array

arr_copy = arr.copy()

arr_copy

# Display array without print method
# Display array using print method
[ 0  1  2  3  4  5  6  7  8  9 10]
# Display the value by array Index without print method
# Display the array elements from index 1 to 5
[1 2 3 4]
#Sclicing array
#Change the value in the slice_of_array


array([ 0,  1, 90, 90,  4,  5,  6,  7,  8,  9, 10])

In [41]:
print ("# Define 2d array")

arr_2d=np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

# Define 2d array


array([1, 2, 3])

In [42]:
arr_2d[0]

array([1, 2, 3])

In [43]:
arr_2d[1]

array([4, 5, 6])

In [45]:
arr_2d[2][2]

9

In [46]:
arr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr_2d[1:2]

array([[4, 5, 6]])

In [97]:
arr_zeros=np.zeros((10,10),dtype=np.int)

arr_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [62]:
arr_zeros_2d=np.zeros((3,10,10), dtype=np.int)
arr_zeros_2d

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [74]:
arr_length=arr_zeros.shape[1]
arr_length1

10

In [75]:
arr_length=arr_zeros.shape[0]
arr_length0

3

In [76]:
arr_length=arr_zeros.shape[2]
arr_length2

10

In [99]:
for i in range(arr_length):
    arr_zeros[i]=1
arr_zeros

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
for i in range(arr_length):
    arr_zeros[i]=i
arr_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [103]:
arr_zeros[[6,2,4,8]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])